### ISSUE TITLE
image converter stop

### ISSUE THREAD

**Issue by T0biasCZe** [Raphael-Boichot/The-Arduino-SD-Game-Boy-Printer#1]
the image convert program stops when the input image doesnt contain all 4 colours (white, light gray, dark gray, and black)
for example, the converter stops at this image:
![obrazek](https://user-images.githubusercontent.com/44525446/131725800-1e26d0dc-cc9c-42c2-a572-03bf1ac2ed1b.png)
but when i add black and dark gray dots on it, it convert fine and continues:
![obrazek](https://user-images.githubusercontent.com/44525446/131725749-88e42d36-c109-4d96-8cdd-4bd5325e60d3.png)

**Comment by Raphael-Boichot** [comment]
Hello.

The code is written by default for 4 colors but can theoretically handle 4, 3 or 2 colors.
I can make a patch I you need it.

Raphael

**Comment by Raphael-Boichot** [comment]
Converter updated, it can now handle 4, 3 or 2 (binary) level grayscales.
