### ISSUE TITLE
esp32

### ISSUE THREAD

**Issue by eried** [Raphael-Boichot/The-Arduino-SD-Game-Boy-Printer#2]
hi! thanks for the code,

1) I wonder what would be the easier way to remove the sd support and just print from memory in an esp32 which has more flash space. What do you think it would be the easier hack? have the image as String?

2) do you have the small "hello" banner.txt file to test?

**Comment by Raphael-Boichot** [comment]
Hello. 
In brief the best way is to use the serial and do everything from outside in an app for example (under dev). I will add the minimal code for doing this soon as is was validated recently on Arduino and Raspberry Pi Pico. Must work on ESP32 too.

The data for banner are here : https://github.com/Raphael-Boichot/The-Arduino-SD-Game-Boy-Printer/blob/master/Game%20Boy%20Printer%20Technical%20data/Hello_Banner_dump.txt

**Comment by eried** [comment]
Thanks! I will try :)

**Comment by Raphael-Boichot** [comment]
Here a generic input/output interface for the Printer. It goes with an Android app that will be published soon.

https://github.com/Raphael-Boichot/The-Arduino-SD-Game-Boy-Printer/tree/master/Research

Basically any external code addressing the serial must work with it.

**Comment by eried** [comment]
Awesome! I will test during the week

**Comment by eried** [comment]
Question, since the only thing it prints is 01 maybe the best approach would be to have some type of command line? i.e.

```
init
line 0000000000110101011110 (or maybe as hex)
end
```

I am thinking on implementing this to output photos from a camera with the esp :D

**Comment by Raphael-Boichot** [comment]
The printer is able to print 4 shades of gray (unlike most thermal printer). You have to use the Game Boy tile format to send your data, no choice. But what you want to do is definitely doable. If you are more interested in general with the printer and the camera, you can join the Game Boy Camera Club (Discord). There are dedicated threads with technical discussions about the printer or ESP/Pico devices. It may be simplier to exchange technical data too.
